[package]
name = "renderer"
version = "0.1.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]
edition = "2021"

[dependencies]
bytemuck = "1.4"
futures = "0.3"
noop-waker = "0.1.0"
winit = "0.25"

[dependencies.png]
version = "0.16"
optional = true

[dependencies.shaderc]
version = "0.7"
optional = true

[dependencies.wgpu]
version = "0.11.0"
features = ["spirv"]

[features]
shader_compilation = ["shaderc"]
capture_to_png = ["png"]
capture_compression = []
all = ["shader_compilation", "capture_to_png", "capture_compression"]
