[package]
name = "renderer"
version = "0.1.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]
edition = "2018"

[dependencies]
bytemuck = "1.4"
futures = "0.3"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs" }
winit = "0.25"

[dependencies.shaderc]
version = "0.7"
optional = true

[features]
shader_compilation = ["shaderc"]

[dev-dependencies]
png = "0.16"
