[package]
name = "renderer"
version = "0.1.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]
edition = "2018"

[dependencies]
bytemuck = "1.3.1"
futures = "0.3.5"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs" }
winit = "0.22.2"

[dependencies.shaderc]
version = "0.6.2"
optional = true

[features]
shader_compilation = ["shaderc"]

[dev-dependencies]
png = "0.15.3"
